Watch page 1차 구현
JaeHye0k/Youtube-Clone pull request #45
Opened 2024-12-20 19:00 UTC by Youjin-K

## 작업내역

-   라우터, 데이터, api, 타입 등 확장
-   비디오 + 컨트롤러, 정보 구현(미완성)

## 주요 변경 사항

-   메인페이지 동영상 클릭 시 시청 페이지로 이동 가능
-   컨트롤 기능과 영상 정보, 채널, 조회수 등 미흡하지만 확인 가능( 수정 시급)

##
내일 오후부터 다시 작업이 가능해서 일단 파일 올려두었습니다..! 팟팅

2024-12-20 23:23 UTC, JaeHye0k commented on src/App.tsx
>      },
`/watch` 경로는 추후에 제거해도 될 것 같아요

2024-12-20 23:43 UTC, JaeHye0k commented on src/hooks/useSubscription.ts
>  export const useSubscription = () => {
사이드바에서 구독한 채널을 보여주는 기능과, 더보기 기능에 필요한 코드가 지워졌네요. 혹시 다른 코드로 분리하신건가요? 아니면 아예 지워진건가요?

2024-12-20 23:43 UTC, JaeHye0k commented on src/stores/videoStore.ts
비디오 업로드시 사용하던 코드들이 제거 됐네요. 혹시 다른 파일로 분리하신건가요? 아니면 아예 지우신건가요?

2024-12-20 23:45 UTC, JaeHye0k requested changes
코멘트 남긴 사항들에 대해 한 번 확인 부탁드립니다

2024-12-21 07:03 UTC, Youjin-K commented on src/stores/videoStore.ts
지운 것 같아서 다시 복구해서 푸시해뒀습니다... 조금 더 잘 확인하고 파일 올리겠습니ㅏㄷ.

2024-12-21 07:17 UTC, Youjin-K commented on src/stores/videoStore.ts
UploadState 인터페이스 추가로 업로드 관련 타입 분리
PlayerStore 인터페이스로 플레이어 관련 타입 분리
VideoStore가 두 인터페이스를 상속하여 전체 스토어 타입 정의

2024-12-21 07:40 UTC, JaeHye0k approved these changes
넵 확인했습니다!

2024-12-21 07:40 UTC, merged